# Generated by Django 5.2.4 on 2026-08-29 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdweb', '0011_alter_preset_config_alter_preset_files'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_public_lightcurves', models.BooleanField(default=False, help_text='Share my measures in the public lightcurves')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LightcurvePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra', models.FloatField()),
                ('dec', models.FloatField()),
                ('filt', models.CharField(max_length=50)),
                ('mag_filter_name', models.CharField(blank=True, max_length=50)),
                ('target_name', models.CharField(blank=True, max_length=250)),
                ('mjd', models.FloatField()),
                ('time_iso', models.CharField(blank=True, max_length=50)),
                ('mag', models.FloatField(blank=True, null=True)),
                ('magerr', models.FloatField(blank=True, null=True)),
                ('mag_limit', models.FloatField(blank=True, null=True)),
                ('is_detection', models.BooleanField(default=False)),
                ('is_diff', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lightcurve_point', to='stdweb.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lightcurve_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['ra', 'dec'], name='stdweb_ligh_ra_a79cf0_idx'), models.Index(fields=['mjd'], name='stdweb_ligh_mjd_9a4d5c_idx'), models.Index(fields=['filt'], name='stdweb_ligh_filt_a43788_idx')],
            },
        ),
    ]
