# Generated by Django 5.2.4 on 2026-08-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdweb', '0012_userprofile_lightcurvepoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_key', models.CharField(max_length=80, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('discovery_mjd', models.FloatField(blank=True, null=True)),
                ('discovery_iso', models.CharField(blank=True, max_length=50)),
                ('tns_url', models.CharField(blank=True, max_length=250)),
                ('source', models.CharField(blank=True, max_length=20)),
                ('fetched', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='affiliation',
            field=models.CharField(blank=True, help_text='Observatory or institute, shown with your name on public pages', max_length=120),
        ),
    ]
