# Generated by Django 5.2.4 on 2026-08-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdweb', '0013_affiliation_alertmeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertmeta',
            name='disc_filter',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='alertmeta',
            name='disc_mag',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alertmeta',
            name='host_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='alertmeta',
            name='obj_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='alertmeta',
            name='redshift',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='alertmeta',
            name='reporting_group',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='alertmeta',
            name='tns_dec',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alertmeta',
            name='tns_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='alertmeta',
            name='tns_ra',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
