# Generated by Django 5.2.4 on 2026-08-29 14:00

from django.db import migrations, models


def publish_existing_shared_points(apps, schema_editor):
    LightcurvePoint = apps.get_model('stdweb', 'LightcurvePoint')
    UserProfile = apps.get_model('stdweb', 'UserProfile')
    sharing = UserProfile.objects.filter(share_public_lightcurves=True).values_list(
        'user_id', flat=True,
    )
    LightcurvePoint.objects.filter(user_id__in=list(sharing)).update(published=True)


class Migration(migrations.Migration):

    dependencies = [
        ('stdweb', '0014_alertmeta_tns_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightcurvepoint',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(publish_existing_shared_points, migrations.RunPython.noop),
    ]
