# Generated by Django 5.2.4 on 2026-08-29 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdweb', '0015_lightcurvepoint_published'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telegram_alert_age_hours',
            field=models.FloatField(
                default=24.0,
                help_text='Expected alert age for a telegram follow-up (hours). Older alerts are flagged in the draft.',
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_radius_arcmin',
            field=models.FloatField(
                default=1.0,
                help_text='Cone radius (arcmin) used to associate a TNS/EP alert with a telegram',
            ),
        ),
        migrations.CreateModel(
            name='TelegramNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(help_text='Alert name (TNS, EP-WXT, …)', max_length=120)),
                ('alert_url', models.CharField(blank=True, max_length=250)),
                ('alert_kind', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('point', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='telegram',
                    to='stdweb.lightcurvepoint',
                )),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='telegram_notices',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
